### ISSUE TITLE
Fracture aperture and permeability values do not affect pressure distributions

### ISSUE THREAD

**Issue by pvh1983** [dfnWorks/dfnWorks-Version2.0#7]
Hello, 

I am playing with constant aperture values (aperture: 3, line 474) in the test "gen_truncated_power_law_dist.dat". However, whatever the aperture values I change, the pressure distributions are the same. Would you please have a look at? 
[gen_truncated_power_law_dist.dat.txt](https://github.com/dfnWorks/dfnWorks-Version2.0/files/1002870/gen_truncated_power_law_dist.dat.txt)

Here is the input file: 

Thank you!
-Hai

**Comment by hymanjd** [comment]
Please send your aperture.dat and prem.dat files

**Comment by hymanjd** [comment]
@pvh1983 If you have constant aperture, and thus constant permeability, then the value of permeability doesn't effect the steady state pressure solution. 

For Laplace's equation

\nabla \cdot k \nabla P =0 

k (permeability) can be pulled out of the divergence operator because it is a constant

Thus you are solving 

k \nabla \cdot \nabla P =0 

which is 

\nabla \cdot \nabla P =0 

However, The effect of different values  of aperture and permeability will be reflected in the velocity values.

**Comment by hymanjd** [comment]
close
